/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defaultToastOptions: typeof import('./src/composables/use-toast').defaultToastOptions
  const defaultToasterProps: typeof import('./src/composables/use-toast').defaultToasterProps
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const getActionToastOptions: typeof import('./src/composables/use-toast').getActionToastOptions
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getDefaultToastOptions: typeof import('./src/composables/use-toast').getDefaultToastOptions
  const getDefaultTypeToastOptions: typeof import('./src/composables/use-toast').getDefaultTypeToastOptions
  const getErrorToastOptions: typeof import('./src/composables/use-toast').getErrorToastOptions
  const getInfoToastOptions: typeof import('./src/composables/use-toast').getInfoToastOptions
  const getLoadingToastOptions: typeof import('./src/composables/use-toast').getLoadingToastOptions
  const getNormalToastOptions: typeof import('./src/composables/use-toast').getNormalToastOptions
  const getSuccessToastOptions: typeof import('./src/composables/use-toast').getSuccessToastOptions
  const getToastConfig: typeof import('./src/composables/use-toast').getToastConfig
  const getWarningToastOptions: typeof import('./src/composables/use-toast').getWarningToastOptions
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setupVueSonner: typeof import('./src/composables/use-toast').setupVueSonner
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const toastConfig: typeof import('./src/composables/use-toast').toastConfig
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useAuth: typeof import('./src/composables/use-auth').useAuth
  const useAuthStore: typeof import('./src/stores/auth.store').useAuthStore
  const useAxios: typeof import('./src/composables/use-axios').useAxios
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useEcho: typeof import('./src/composables/use-echo').useEcho
  const useErrorStore: typeof import('./src/stores/error.store').useErrorStore
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useReverbNotifications: typeof import('./src/composables/use-reverb-notifications').useReverbNotifications
  const useRoute: typeof import('vue-router').useRoute
  const useRouteHelper: typeof import('./src/composables/use-route-helper').useRouteHelper
  const useRouter: typeof import('vue-router').useRouter
  const useSeoMetaTags: typeof import('./src/composables/use-seo-meta-tags').useSeoMetaTags
  const useSidebar: typeof import('./src/composables/use-sidebar').useSidebar
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemeStore: typeof import('./src/stores/theme.store').useThemeStore
  const useToast: typeof import('./src/composables/use-toast').useToast
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ErrorType, ErrorState, SetErrorOptions } from './src/stores/error.store'
  import('./src/stores/error.store')
}
