<script lang="ts" setup>
import type { DateValue } from '@internationalized/date'

import {
  CalendarDateTime,
  DateFormatter,
  getLocalTimeZone,
  parseAbsoluteToLocal,
} from '@internationalized/date'
import { toTypedSchema } from '@vee-validate/zod'
import { Calendar as CalendarIcon } from 'lucide-vue-next'
import { useForm } from 'vee-validate'
import { toast } from 'vue-sonner'
import { z } from 'zod'

import { Calendar } from '@/components/ui/calendar'
import { Checkbox } from '@/components/ui/checkbox'
import { FormField } from '@/components/ui/form'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import { cn } from '@/lib/utils'

import type { Task } from '../data/schema'

import { labels, priorities, statuses } from '../data/data'

const props = defineProps<{
  task: Task | null
}>()
const emits = defineEmits<{
  'close': []
  'task-updated': [task: Task]
  'task-created': [task: Task]
}>()

const df = new DateFormatter('en-US', {
  dateStyle: 'medium',
})

const dueDate = ref<DateValue | undefined>()
const dueTime = ref<string | undefined>('00:00')

// Initialize due date from task
if (props.task?.dueDate) {
  if (typeof props.task.dueDate === 'string') {
    dueDate.value = parseAbsoluteToLocal(props.task.dueDate)
    if (dueDate.value) {
      dueTime.value = `${dueDate.value.hour < 10 ? `0${dueDate.value?.hour}` : dueDate.value?.hour}:${dueDate.value.minute < 10 ? `0${dueDate.value?.minute}` : dueDate.value?.minute}`
    }
  }
}

watch(
  () => dueTime.value,
  (newVal) => {
    if (!newVal)
      return
    if (dueDate.value) {
      const [hours, minutes] = newVal.split(':').map(Number)
      dueDate.value = new CalendarDateTime(
        dueDate.value.year,
        dueDate.value.month,
        dueDate.value.day,
        hours,
        minutes,
      )
    }
  },
)

const formSchema = toTypedSchema(
  z.object({
    title: z
      .string()
      .min(2)
      .max(50)
      .default(props.task?.title ?? ''),
    description: z
      .string()
      .optional()
      .default(props.task?.description ?? ''),
    status: z.string().default(props.task?.status ?? ''),
    labels: z.array(z.string()).default(props.task?.labels ?? []),
    priority: z.string().default(props.task?.priority ?? ''),
    dueDate: z.union([z.string(), z.number(), z.date()]).optional(),
  }),
)

const { isFieldDirty, handleSubmit } = useForm({
  validationSchema: formSchema,
})
const onSubmit = handleSubmit((values) => {
  const submitValues = {
    ...values,
    dueDate: dueDate.value
      ? dueDate.value.toDate(getLocalTimeZone())
      : undefined,
  }

  // If editing existing task, emit update event
  if (props.task?.id) {
    emits('task-updated', {
      ...props.task,
      ...submitValues,
    })
  } else {
    // Creating new task, emit create event
    emits('task-created', {
      id: '', // Will be generated by the handler
      ...submitValues,
      createdAt: new Date().toISOString(),
    } as Task)
  }

  toast('You submitted the following values:', {
    description: h(
      'pre',
      { class: 'mt-2 w-[340px] rounded-md bg-slate-950 p-4' },
      h('code', { class: 'text-white' }, JSON.stringify(submitValues, null, 2)),
    ),
  })
  emits('close')
})
</script>

<template>
  <div>
    <form class="w-2/3 space-y-6" @submit="onSubmit">
      <FormField
        v-slot="{ componentField }"
        name="title"
        :validate-on-blur="!isFieldDirty"
      >
        <UiFormItem>
          <UiFormLabel>Title</UiFormLabel>
          <UiFormControl>
            <UiInput
              type="text"
              placeholder="Enter task title"
              v-bind="componentField"
            />
          </UiFormControl>
          <UiFormDescription />
          <UiFormMessage />
        </UiFormItem>
      </FormField>
      <FormField
        v-slot="{ componentField }"
        name="description"
        :validate-on-blur="!isFieldDirty"
      >
        <UiFormItem>
          <UiFormLabel>Description</UiFormLabel>
          <UiFormControl>
            <UiTextarea
              placeholder="Enter task description (optional)"
              rows="4"
              v-bind="componentField"
            />
          </UiFormControl>
          <UiFormDescription />
          <UiFormMessage />
        </UiFormItem>
      </FormField>
      <FormField
        v-slot="{ componentField }"
        name="status"
        :validate-on-blur="!isFieldDirty"
      >
        <UiFormItem>
          <UiFormLabel>Status</UiFormLabel>
          <UiFormControl>
            <UiSelect v-bind="componentField">
              <UiSelectTrigger class="w-[180px]">
                <UiSelectValue placeholder="Select a status" />
              </UiSelectTrigger>
              <UiSelectContent>
                <UiSelectGroup>
                  <UiSelectItem
                    v-for="status in statuses"
                    :key="status.value"
                    :value="status.value"
                  >
                    <div class="flex items-center gap-2">
                      <component :is="status.icon" class="size-4 shrink-0" />
                      {{ status.label }}
                    </div>
                  </UiSelectItem>
                </UiSelectGroup>
              </UiSelectContent>
            </UiSelect>
          </UiFormControl>
          <UiFormDescription />
          <UiFormMessage />
        </UiFormItem>
      </FormField>
      <FormField
        v-slot="{ componentField }"
        name="labels"
        :validate-on-blur="!isFieldDirty"
      >
        <UiFormItem>
          <UiFormLabel>Labels</UiFormLabel>
          <UiFormControl>
            <div class="flex flex-col space-y-2">
              <UiFormItem
                v-for="label in labels"
                :key="label.value"
                class="flex items-center space-y-0 gap-x-3"
              >
                <UiFormControl>
                  <Checkbox
                    :checked="componentField.modelValue?.includes(label.value)"
                    @update:checked="
                      (checked) => {
                        const current = componentField.modelValue || []
                        if (checked) {
                          componentField.modelValue = [...current, label.value]
                        }
                        else {
                          componentField.modelValue = current.filter(
                            (l: string) => l !== label.value,
                          )
                        }
                      }
                    "
                  />
                </UiFormControl>
                <UiFormLabel class="font-normal">
                  {{ label.label }}
                </UiFormLabel>
              </UiFormItem>
            </div>
          </UiFormControl>
          <UiFormDescription />
          <UiFormMessage />
        </UiFormItem>
      </FormField>
      <FormField
        v-slot="{ componentField }"
        name="priority"
        :validate-on-blur="!isFieldDirty"
      >
        <UiFormItem>
          <UiFormLabel>Priority</UiFormLabel>
          <UiFormControl>
            <UiRadioGroup
              class="flex flex-col space-y-1"
              v-bind="componentField"
            >
              <UiFormItem
                v-for="priority in priorities"
                :key="priority.value"
                class="flex items-center space-y-0 gap-x-3"
              >
                <UiFormControl>
                  <UiRadioGroupItem :value="priority.value" />
                </UiFormControl>
                <UiFormLabel class="font-normal">
                  {{ priority.label }}
                </UiFormLabel>
              </UiFormItem>
            </UiRadioGroup>
          </UiFormControl>
          <UiFormDescription />
          <UiFormMessage />
        </UiFormItem>
      </FormField>
      <FormField name="dueDate" :validate-on-blur="!isFieldDirty">
        <UiFormItem>
          <UiFormLabel>Due Date</UiFormLabel>
          <UiFormControl>
            <div class="flex items-center gap-1">
              <Popover>
                <PopoverTrigger as-child>
                  <UiButton
                    variant="outline"
                    :class="
                      cn(
                        'flex-1 justify-start text-left font-normal px-3',
                        !dueDate && 'text-muted-foreground',
                      )
                    "
                  >
                    <CalendarIcon class="mr-2 size-4" />
                    {{
                      dueDate
                        ? df.format(dueDate.toDate(getLocalTimeZone()))
                        : 'Pick a date'
                    }}
                  </UiButton>
                </PopoverTrigger>
                <PopoverContent class="w-auto p-0">
                  <Calendar v-model="dueDate" initial-focus />
                </PopoverContent>
              </Popover>
              <UiInput
                id="time-picker"
                v-model="dueTime"
                type="time"
                step="60"
                default-value="00:00"
                class="flex-1 bg-background appearance-none [&::-webkit-calendar-picker-indicator]:hidden [&::-webkit-calendar-picker-indicator]:appearance-none"
              />
            </div>
          </UiFormControl>
          <UiFormDescription />
          <UiFormMessage />
        </UiFormItem>
      </FormField>

      <UiButton type="submit">
        Submit
      </UiButton>
    </form>
  </div>
</template>
